Cansu.Northwind.MVCWebUI/Controllers/ProductController.cs
using Cansu.Northwind.Business.Abstract;
using Cansu.Northwind.MVCWebUI.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cansu.Northwind.MVCWebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }
        public IActionResult Index(int page=1, int category=0)
        {
            int pageSize = 10;
            var products = _productService.GetByCategory(category);

            ProductListViewModel model = new ProductListViewModel
            {
                Products = products.Skip((page - 1) * pageSize).Take(pageSize).ToList(),
                PageCount = (int) Math.Ceiling(products.Count/(double) pageSize),
                PageSize = pageSize,
                CurrentCategory = category,
                CurrentPage = page
            };
            return View(model);
        }
    }
}

Cansu.Northwind.MVCWebUI/ViewComponents/CartSummaryViewComponent.cs
using Cansu.Northwind.MVCWebUI.Models;
using Cansu.Northwind.MVCWebUI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cansu.Northwind.MVCWebUI.ViewComponents
{
    public class CartSummaryViewComponent:ViewComponent
    {
        private ICartSessionService _cartSessionService;

        public CartSummaryViewComponent(ICartSessionService cartSessionService)
        {
            _cartSessionService = cartSessionService;
        }

        public ViewViewComponentResult Invoke()
        {
            var model = new CartSummaryViewModel
            {
                Cart = _cartSessionService.GetCart()
            };

        return View(model);
        }
    }
}

Cansu.Northwind.MVCWebUI/ViewComponents/CategoryListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cansu.Northwind.Business.Abstract;
using Cansu.Northwind.MVCWebUI.Models;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace Cansu.Northwind.MVCWebUI.ViewComponents
{
    public class CategoryListViewComponent:ViewComponent
    {
        ICategoryService _categoryService;

        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public ViewViewComponentResult Invoke()
        {
            var categories = _categoryService.GetAll();

            CategoryListViewModel model = new CategoryListViewModel
            {
                Categories = categories,
                CurrentCategory = Convert.ToInt32(HttpContext.Request.Query["category"])
            };
            return View(model);
        }
    }
}

Cansu.Northwind.MVCWebUI/ViewComponents/UserSummaryViewComponent.cs
using Cansu.Northwind.MVCWebUI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cansu.Northwind.MVCWebUI.ViewComponents
{
    public class UserSummaryViewComponent:ViewComponent
    {
        public ViewViewComponentResult Invoke()
        {
            UserDetailsViewModel model = new UserDetailsViewModel
            {
                UserName = HttpContext.User.Identity.Name
            };
            return View(model);
        }
    }
}

Cansu.Northwind.MVCWebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

</head>

<body>
    <div class="col-md-12" style="margin-bottom:20px">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Northwind Admin Panel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item active"><a class="nav-link" asp-controller="Product" asp-action="Index">Products Store<span class="sr-only">(current)</span></a></li>
                    </ul>
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 navbar-right">
                        <li class="dropdown">
                            @await Component.InvokeAsync("UserSummary")
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="col-md-12">
            @if (TempData["message"] != null)
            {
                <div class="alert alert-info" role="alert">@TempData["message"]</div>
            }
            @RenderBody()
        </div>
    </div>

</body>
</html>

Cansu.Northwind.MVCWebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

</head>

<body>
    <div class="col-md-12" style="margin-bottom:20px">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Northwind</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item active"><a class="nav-link" asp-controller="Account" asp-action="Login">Admin<span class="sr-only">(current)</span></a></li>
                    </ul>
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 navbar-right">
                        <li class="dropdown">
                            @await Component.InvokeAsync("CartSummary")
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="row container-fluid">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryList")
        </div>
        <div class="col-md-9">
            @if (TempData["message"] != null)
            {
                <div class="alert alert-info" role="alert">@TempData["message"]</div>
            }
            @RenderBody()
        </div>
    </div>

</body>
</html>